//auth
export const LOG_IN='LOG_IN';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const LOG_OUT = 'LOG_OUT';
//CRUD
export const CREATE_SUBMIT='CREATE_SUBMIT';//Create
export const ID_DELETE='ID_DELETE';//Delete
export const ID_DELETE_ERROR='ID_DELETE_ERROR';//Delete error
export const UPDATE_SUBMIT='UPDATE_SUBMIT';//Update
export const UPDATE_SUBMIT_ERROR='UPDATE_SUBMIT_ERROR';//Update error
export const ID_QUERY='ID_QUERY';//Retrieve
export const ID_QUERY_ERROR='ID_QUERY_ERROR';//Retrieve error
//roles info
export const LOAD_HEADER_PORTRAIT_URL='LOAD_HEADER_PORTRAIT_URL';
//test
export const INCREMENT='INCREMENT';
export const DECREMENT='DECREMENT';

//hive_front_staffing_system
export const GET_ALL_STAFF_INFO='GET_ALL_STAFF_INFO';
// export const GET_POST='GET_POST';
// export const GET_DEPARTMENT='GET_DEPARTMENT';
export const GET_POST_MAP_DEPARTMENT='GET_POST_MAP_DEPARTMENT'; //部门与职位的映射表，用的较多，直接后台生成
export const GET_POST_CASCADER='GET_POST_CASCADER'; //部门与职位的级联瀑布对象
export const GET_CLOCK_IN='GET_CLOCK_IN';
export const GET_DEPARTMENT_ATTENDANCE_RATE='GET_DEPARTMENT_ATTENDANCE_RATE';
export const GET_ATTENDANCE='GET_ATTENDANCE';
export const GET_DEPARTMENT_FILE_LIST='GET_DEPARTMENT_FILE_LIST';
export const UPDATE_FILE_NAME='UPDATE_FILE_NAME';
export const DELETE_FILE='DELETE_FILE';
export const UPDATE_STAFF='UPDATE_STAFF';
export const DELETE_STAFF='DELETE_STAFF';
export const CREATE_STAFF='CREATE_STAFF';
export const UPDATE_ASSOCIATION='UPDATE_ASSOCIATION';
export const DELETE_ASSOCIATION='DELETE_ASSOCIATION';
export const CREATE_ASSOCIATION='CREATE_ASSOCIATION';
export const TEST='TEST';
export const INIT='INIT';
export const CLEAR_CLOCK_IN_RATE='CLEAR_CLOCK_IN_RATE';
export const CLEAR_DEPARTMENT_ATTENDANCE_RATE='CLEAR_DEPARTMENT_ATTENDANCE_RATE';
