export const INCREMENT='INCREMENT';
export const DECREMENT='DECREMENT';
export const ID_QUERY='ID_QUERY';
export const ID_QUERY_ERROR='ID_QUERY_ERROR';
export const CREATE_SUBMIT='CREATE_SUBMIT';
export const UPDATE_SUBMIT='UPDATE_SUBMIT';
export const UPDATE_SUBMIT_ERROR='UPDATE_SUBMIT_ERROR';
export const ID_DELETE='ID_DELETE';
export const ID_DELETE_ERROR='ID_DELETE_ERROR';

